vacation = ['dubai', 'uk', 'tanzania', 'mauritius', 'japan']
print('Here is the original list:')
print(vacation)
sorted_vacation = sorted(vacation)
print('\nHere is the sorted list:') 
print(sorted_vacation)
print('\nHere is the original list again:')
print(vacation)
reverse_vacation = sorted(vacation, reverse=True)
print('\nHere is the reverse-alphabetical list')
print(reverse_vacation)
print('\nHere is the original list again')
print(vacation)
vacation.reverse()
print('\nHere is the reversed permanantly changed list:')
print(vacation)
vacation.reverse()
print('\nHere is the list reversed back to normal:')
print(vacation)
print('\n')
print('This will now be considered the original list:')
print(vacation)
print('\n')
vacation.sort()
print(f'Here is the list alphabetically sorted: \n{vacation}')
print('\n')
vacation.sort(reverse=True)
print(f'Here is the list sorted alphabetically in reverse:\n{vacation}')
print('\n')
print(len(vacation))